[build]
  publish = "."

[[redirects]]
  from = "/app"
  to = "https://majestic-empanada-18482c.netlify.app/app"
  status = 200
  force = true

[[redirects]]
  from = "/admin"
  to = "https://majestic-empanada-18482c.netlify.app/admin"
  status = 200
  force = true